import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home.component';
import { LoginComponent } from './pages/login/login.component';
import { DashboardComponent } from './pages/dashboard/dashboard.component';
import { BusManagementComponent } from './pages/bus-management/bus-management.component';
import { AddBusComponent } from './pages/bus-management/add-bus.component';
import { EditBusComponent } from './pages/bus-management/edit-bus.component';
import { DriverManagementComponent } from './pages/driver-management/driver-management.component';
import { AddDriverComponent } from './pages/driver-management/add-driver.component';
import { EditDriverComponent } from './pages/driver-management/edit-driver.component';
import { PassengerManagementComponent } from './pages/passenger-management/passenger-management.component';
import { AddPassengerComponent } from './pages/passenger-management/add-passenger.component';
import { EditPassengerComponent } from './pages/passenger-management/edit-passenger.component';
import { LoungesManagementComponent } from './pages/lounge-management/lounges-management.component';
import { AddLoungeComponent } from './pages/lounge-management/add-lounge.component';
import { EditLoungeComponent } from './pages/lounge-management/edit-lounge.component';
import { ViewLoungeComponent } from './pages/lounge-management/view-lounge.component';


export const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'home', component: HomeComponent },
  { path: 'login', component: LoginComponent },
  { path: 'dashboard', component: DashboardComponent },
  { path: 'bus-management', component: BusManagementComponent },
  { path: 'bus-management/add', component: AddBusComponent },
  { path: 'bus-management/edit/:id', component: EditBusComponent },
  { path: 'driver-management', component: DriverManagementComponent },
  { path: 'driver-management/add', component: AddDriverComponent },
  { path: 'driver-management/edit/:id', component: EditDriverComponent },
  { path: 'passenger-management', component: PassengerManagementComponent },
  { path: 'passenger-management/add', component: AddPassengerComponent },
  { path: 'passenger-management/edit/:id', component: EditPassengerComponent },
  { path: 'lounges-management', component: LoungesManagementComponent },
  { path: 'lounges-management/view/:id', component: ViewLoungeComponent },
  { path: 'add-lounge', component: AddLoungeComponent },
  { path: 'lounges-management/edit/:id', component: EditLoungeComponent },
  { path: 'lounges-management/view/:id', component: ViewLoungeComponent },
  { path: '**', redirectTo: '' }
];
